// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLth86Z-xH_Ynn5GP6KL3CyyBcLSYfr0',
    appId: '1:933005671020:web:aeeb0ac4df520016cb7649',
    messagingSenderId: '933005671020',
    projectId: 'movie-app-ee46d',
    authDomain: 'movie-app-ee46d.firebaseapp.com',
    storageBucket: 'movie-app-ee46d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tsxkHRBpNgHAUZXyUMTEX6Nd7lS6Rs4',
    appId: '1:933005671020:android:5eafb72f968c58ffcb7649',
    messagingSenderId: '933005671020',
    projectId: 'movie-app-ee46d',
    storageBucket: 'movie-app-ee46d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvBiM8lKPcmwJaXm25Tmyhib7VcnViw0',
    appId: '1:933005671020:ios:de2a56c545a7ee3ccb7649',
    messagingSenderId: '933005671020',
    projectId: 'movie-app-ee46d',
    storageBucket: 'movie-app-ee46d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZvBiM8lKPcmwJaXm25Tmyhib7VcnViw0',
    appId: '1:933005671020:ios:de2a56c545a7ee3ccb7649',
    messagingSenderId: '933005671020',
    projectId: 'movie-app-ee46d',
    storageBucket: 'movie-app-ee46d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQLth86Z-xH_Ynn5GP6KL3CyyBcLSYfr0',
    appId: '1:933005671020:web:620c461fcb08995fcb7649',
    messagingSenderId: '933005671020',
    projectId: 'movie-app-ee46d',
    authDomain: 'movie-app-ee46d.firebaseapp.com',
    storageBucket: 'movie-app-ee46d.appspot.com',
  );
}
